const fs = require('fs');

let html = fs.readFileSync('index.html', 'utf8');

const newDb = `    const plantDatabase = [
      // MEDICINAL
      { name: "Aloe Vera (Medicinal)", scientific: "Aloe barbadensis miller", icon: "🪴", freq: 14, health: [{icon:"🧴", text:"Soothes Skin"}, {icon:"✨", text:"Purifies Air"}] },
      { name: "Holy Basil / Tulsi", scientific: "Ocimum tenuiflorum", icon: "🌿", freq: 2, health: [{icon:"🛡️", text:"Immunity Booster"}, {icon:"🫁", text:"Respiratory Health"}] },
      { name: "Ashwagandha", scientific: "Withania somnifera", icon: "🪴", freq: 5, health: [{icon:"😌", text:"Reduces Anxiety"}, {icon:"💤", text:"Improves Sleep"}] },
      { name: "Neem", scientific: "Azadirachta indica", icon: "🌳", freq: 7, health: [{icon:"🦠", text:"Antibacterial"}, {icon:"🩸", text:"Blood Purifier"}] },
      { name: "Turmeric", scientific: "Curcuma longa", icon: "🌱", freq: 4, health: [{icon:"🔥", text:"Anti-inflammatory"}, {icon:"🛡️", text:"Immunity"}] },
      { name: "Ginger", scientific: "Zingiber officinale", icon: "🌿", freq: 4, health: [{icon:"🤢", text:"Nausea Relief"}, {icon:"🔥", text:"Anti-inflammatory"}] },
      { name: "Gotu Kola", scientific: "Centella asiatica", icon: "🍀", freq: 2, health: [{icon:"🧠", text:"Brain Health"}, {icon:"🩸", text:"Circulation"}] },
      { name: "Echinacea", scientific: "Echinacea purpurea", icon: "🌸", freq: 5, health: [{icon:"🛡️", text:"Immune Support"}, {icon:"🤧", text:"Cold Relief"}] },
      { name: "Chamomile", scientific: "Matricaria chamomilla", icon: "🌼", freq: 3, health: [{icon:"💤", text:"Sleep Aid"}, {icon:"😌", text:"Calming"}] },
      { name: "Lavender", scientific: "Lavandula", icon: "🪻", freq: 7, health: [{icon:"😌", text:"Stress Relief"}, {icon:"💤", text:"Better Sleep"}] },
      { name: "Peppermint", scientific: "Mentha × piperita", icon: "🍃", freq: 2, health: [{icon:"🌿", text:"Aids Digestion"}, {icon:"🤕", text:"Headache Relief"}] },
      { name: "Lemon Balm", scientific: "Melissa officinalis", icon: "🌿", freq: 3, health: [{icon:"😌", text:"Calms Anxiety"}, {icon:"🧠", text:"Cognitive Boost"}] },
      { name: "Calendula", scientific: "Calendula officinalis", icon: "🏵️", freq: 3, health: [{icon:"🧴", text:"Skin Healing"}, {icon:"🔥", text:"Anti-inflammatory"}] },
      { name: "Ginseng", scientific: "Panax ginseng", icon: "🌱", freq: 5, health: [{icon:"⚡", text:"Energy Boost"}, {icon:"🧠", text:"Memory"}] },
      { name: "Valerian", scientific: "Valeriana officinalis", icon: "🌿", freq: 3, health: [{icon:"💤", text:"Treats Insomnia"}, {icon:"😌", text:"Anxiety Relief"}] },
      { name: "St. John's Wort", scientific: "Hypericum perforatum", icon: "🌼", freq: 4, health: [{icon:"😊", text:"Mood Elevator"}, {icon:"🩹", text:"Wound Healing"}] },
      { name: "Dandelion", scientific: "Taraxacum", icon: "🌼", freq: 2, health: [{icon:"🩸", text:"Liver Detox"}, {icon:"💧", text:"Diuretic"}] },
      { name: "Milk Thistle", scientific: "Silybum marianum", icon: "🌿", freq: 5, health: [{icon:"🩸", text:"Liver Health"}, {icon:"🛡️", text:"Antioxidant"}] },
      { name: "Rosemary", scientific: "Salvia rosmarinus", icon: "🌿", freq: 7, health: [{icon:"🧠", text:"Memory Boost"}, {icon:"💇", text:"Hair Growth"}] },
      { name: "Thyme", scientific: "Thymus vulgaris", icon: "🌿", freq: 7, health: [{icon:"🫁", text:"Cough Relief"}, {icon:"🦠", text:"Antibacterial"}] },
      { name: "Oregano", scientific: "Origanum vulgare", icon: "🍃", freq: 5, health: [{icon:"🦠", text:"Antimicrobial"}, {icon:"🛡️", text:"Antioxidant"}] },
      { name: "Sage", scientific: "Salvia officinalis", icon: "🌿", freq: 7, health: [{icon:"🧠", text:"Brain Health"}, {icon:"🫁", text:"Soothes Throat"}] },
      { name: "Brahmi", scientific: "Bacopa monnieri", icon: "🌱", freq: 2, health: [{icon:"🧠", text:"Memory Enhancer"}, {icon:"😌", text:"Reduces Stress"}] },
      { name: "Moringa", scientific: "Moringa oleifera", icon: "🌳", freq: 7, health: [{icon:"⚡", text:"Highly Nutritious"}, {icon:"🔥", text:"Anti-inflammatory"}] },
      { name: "Amla (Indian Gooseberry)", scientific: "Phyllanthus emblica", icon: "🌳", freq: 5, health: [{icon:"✨", text:"Vitamin C Rich"}, {icon:"🛡️", text:"Immunity"}] },
      { name: "Guduchi", scientific: "Tinospora cordifolia", icon: "🌿", freq: 4, health: [{icon:"🛡️", text:"Immunity Booster"}, {icon:"🔥", text:"Anti-inflammatory"}] },
      { name: "Shatavari", scientific: "Asparagus racemosus", icon: "🌱", freq: 3, health: [{icon:"♀️", text:"Women's Health"}, {icon:"⚡", text:"Vitality"}] },
      { name: "Licorice", scientific: "Glycyrrhiza glabra", icon: "🌿", freq: 4, health: [{icon:"🫁", text:"Respiratory Health"}, {icon:"🔥", text:"Anti-inflammatory"}] },
      { name: "Fennel", scientific: "Foeniculum vulgare", icon: "🌱", freq: 3, health: [{icon:"🌿", text:"Aids Digestion"}, {icon:"🩸", text:"Blood Pressure"}] },
      { name: "Coriander", scientific: "Coriandrum sativum", icon: "🌿", freq: 2, health: [{icon:"🌿", text:"Aids Digestion"}, {icon:"🩸", text:"Lowers Blood Sugar"}] },

      // VEGETABLES
      { name: "Tomato", scientific: "Solanum lycopersicum", icon: "🍅", freq: 2, health: [{icon:"❤️", text:"Heart Health"}, {icon:"👀", text:"Vision Support"}] },
      { name: "Cherry Tomato", scientific: "Solanum lycopersicum var. cerasiforme", icon: "🍅", freq: 2, health: [{icon:"🛡️", text:"Antioxidants"}] },
      { name: "Spinach", scientific: "Spinacia oleracea", icon: "🥬", freq: 2, health: [{icon:"💪", text:"Iron Rich"}, {icon:"👀", text:"Eye Health"}] },
      { name: "Kale", scientific: "Brassica oleracea var. sabellica", icon: "🥬", freq: 2, health: [{icon:"🛡️", text:"High Antioxidants"}, {icon:"🦴", text:"Bone Health"}] },
      { name: "Carrot", scientific: "Daucus carota", icon: "🥕", freq: 3, health: [{icon:"👀", text:"Vision Health"}, {icon:"✨", text:"Beta Carotene"}] },
      { name: "Broccoli", scientific: "Brassica oleracea var. italica", icon: "🥦", freq: 3, health: [{icon:"🛡️", text:"Cancer Prevention"}, {icon:"✨", text:"Vitamin K"}] },
      { name: "Bell Pepper", scientific: "Capsicum annuum", icon: "🫑", freq: 3, health: [{icon:"✨", text:"Vitamin C"}, {icon:"👀", text:"Eye Health"}] },
      { name: "Chili Pepper", scientific: "Capsicum frutescens", icon: "🌶️", freq: 3, health: [{icon:"🔥", text:"Metabolism Boost"}, {icon:"🤕", text:"Pain Relief"}] },
      { name: "Cucumber", scientific: "Cucumis sativus", icon: "🥒", freq: 2, health: [{icon:"💧", text:"Hydration"}, {icon:"✨", text:"Skin Health"}] },
      { name: "Zucchini", scientific: "Cucurbita pepo", icon: "🥒", freq: 2, health: [{icon:"🌿", text:"Digestion"}, {icon:"❤️", text:"Heart Health"}] },
      { name: "Eggplant", scientific: "Solanum melongena", icon: "🍆", freq: 3, health: [{icon:"🧠", text:"Brain Health"}, {icon:"🛡️", text:"Antioxidants"}] },
      { name: "Onion", scientific: "Allium cepa", icon: "🧅", freq: 4, health: [{icon:"🛡️", text:"Immune Support"}, {icon:"❤️", text:"Heart Health"}] },
      { name: "Garlic", scientific: "Allium sativum", icon: "🧄", freq: 4, health: [{icon:"🦠", text:"Antibacterial"}, {icon:"❤️", text:"Lowers BP"}] },
      { name: "Potato", scientific: "Solanum tuberosum", icon: "🥔", freq: 4, health: [{icon:"⚡", text:"Energy"}, {icon:"🍌", text:"Potassium Rich"}] },
      { name: "Sweet Potato", scientific: "Ipomoea batatas", icon: "🍠", freq: 4, health: [{icon:"👀", text:"Vision Support"}, {icon:"🩸", text:"Blood Sugar Control"}] },
      { name: "Radish", scientific: "Raphanus sativus", icon: "🥗", freq: 2, health: [{icon:"🩸", text:"Detoxifies Blood"}, {icon:"🌿", text:"Digestion"}] },
      { name: "Beetroot", scientific: "Beta vulgaris", icon: "🥗", freq: 3, health: [{icon:"❤️", text:"Lowers BP"}, {icon:"🏃", text:"Athletic Performance"}] },
      { name: "Cabbage", scientific: "Brassica oleracea var. capitata", icon: "🥬", freq: 3, health: [{icon:"🔥", text:"Anti-inflammatory"}, {icon:"🌿", text:"Digestion"}] },
      { name: "Cauliflower", scientific: "Brassica oleracea var. botrytis", icon: "🥦", freq: 3, health: [{icon:"🛡️", text:"Antioxidants"}, {icon:"🧠", text:"Choline Source"}] },
      { name: "Peas", scientific: "Pisum sativum", icon: "🫛", freq: 3, health: [{icon:"💪", text:"Plant Protein"}, {icon:"🌿", text:"High Fiber"}] },
      { name: "Green Beans", scientific: "Phaseolus vulgaris", icon: "🫘", freq: 3, health: [{icon:"❤️", text:"Heart Health"}, {icon:"🦴", text:"Bone Health"}] },
      { name: "Pumpkin", scientific: "Cucurbita", icon: "🎃", freq: 4, health: [{icon:"👀", text:"Vision Support"}, {icon:"🛡️", text:"Immunity"}] },
      { name: "Lettuce", scientific: "Lactuca sativa", icon: "🥬", freq: 2, health: [{icon:"💧", text:"Hydration"}, {icon:"💤", text:"Sleep Aid"}] },
      { name: "Corn", scientific: "Zea mays", icon: "🌽", freq: 3, health: [{icon:"👀", text:"Eye Health"}, {icon:"🌿", text:"High Fiber"}] },
      { name: "Asparagus", scientific: "Asparagus officinalis", icon: "🥗", freq: 3, health: [{icon:"💧", text:"Diuretic"}, {icon:"🤰", text:"Folate Rich"}] },

      // FRUITS
      { name: "Strawberry", scientific: "Fragaria × ananassa", icon: "🍓", freq: 2, health: [{icon:"✨", text:"Vitamin C"}, {icon:"🧠", text:"Brain Health"}] },
      { name: "Blueberry", scientific: "Vaccinium corymbosum", icon: "🫐", freq: 3, health: [{icon:"🛡️", text:"Super Antioxidant"}, {icon:"🧠", text:"Brain Boost"}] },
      { name: "Raspberry", scientific: "Rubus idaeus", icon: "🍓", freq: 3, health: [{icon:"🌿", text:"High Fiber"}, {icon:"🔥", text:"Anti-inflammatory"}] },
      { name: "Blackberry", scientific: "Rubus", icon: "🫐", freq: 3, health: [{icon:"🦷", text:"Oral Health"}, {icon:"🧠", text:"Brain Health"}] },
      { name: "Apple", scientific: "Malus domestica", icon: "🍎", freq: 5, health: [{icon:"❤️", text:"Heart Health"}, {icon:"🌿", text:"Aids Digestion"}] },
      { name: "Lemon", scientific: "Citrus limon", icon: "🍋", freq: 5, health: [{icon:"✨", text:"Vitamin C"}, {icon:"💧", text:"Hydration"}] },
      { name: "Orange", scientific: "Citrus × sinensis", icon: "🍊", freq: 5, health: [{icon:"🛡️", text:"Immune Support"}, {icon:"✨", text:"Skin Health"}] },
      { name: "Banana", scientific: "Musa", icon: "🍌", freq: 4, health: [{icon:"⚡", text:"Energy"}, {icon:"❤️", text:"Heart Health"}] },
      { name: "Watermelon", scientific: "Citrullus lanatus", icon: "🍉", freq: 3, health: [{icon:"💧", text:"Hydration"}, {icon:"💪", text:"Muscle Soreness Relief"}] },
      { name: "Grapes", scientific: "Vitis vinifera", icon: "🍇", freq: 4, health: [{icon:"🛡️", text:"Antioxidants"}, {icon:"❤️", text:"Heart Health"}] },
      { name: "Mango", scientific: "Mangifera indica", icon: "🥭", freq: 5, health: [{icon:"🛡️", text:"Immune Boost"}, {icon:"🌿", text:"Digestion"}] },
      { name: "Pineapple", scientific: "Ananas comosus", icon: "🍍", freq: 4, health: [{icon:"🔥", text:"Anti-inflammatory"}, {icon:"🌿", text:"Digestion"}] },
      { name: "Peach", scientific: "Prunus persica", icon: "🍑", freq: 4, health: [{icon:"✨", text:"Skin Health"}, {icon:"🌿", text:"Digestion"}] },
      { name: "Cherry", scientific: "Prunus avium", icon: "🍒", freq: 4, health: [{icon:"💤", text:"Sleep Aid (Melatonin)"}, {icon:"🔥", text:"Anti-inflammatory"}] },
      { name: "Avocado", scientific: "Persea americana", icon: "🥑", freq: 5, health: [{icon:"❤️", text:"Healthy Fats"}, {icon:"👀", text:"Vision Support"}] },
      { name: "Papaya", scientific: "Carica papaya", icon: "🥭", freq: 4, health: [{icon:"🌿", text:"Digestion (Papain)"}, {icon:"✨", text:"Skin Health"}] },
      { name: "Pomegranate", scientific: "Punica granatum", icon: "🍎", freq: 5, health: [{icon:"🛡️", text:"Powerful Antioxidants"}, {icon:"❤️", text:"Heart Health"}] },
      { name: "Kiwi", scientific: "Actinidia deliciosa", icon: "🥝", freq: 3, health: [{icon:"✨", text:"Vitamin C"}, {icon:"💤", text:"Sleep Quality"}] },
      { name: "Fig", scientific: "Ficus carica", icon: "🌳", freq: 4, health: [{icon:"🌿", text:"High Fiber"}, {icon:"🦴", text:"Bone Health"}] },
      { name: "Olive", scientific: "Olea europaea", icon: "🫒", freq: 7, health: [{icon:"❤️", text:"Heart Health"}, {icon:"🔥", text:"Anti-inflammatory"}] },

      // INDOOR / AIR PURIFYING
      { name: "Snake Plant", scientific: "Sansevieria trifasciata", icon: "🪴", freq: 14, health: [{icon:"🌬️", text:"Night Air Purifier"}, {icon:"✨", text:"Removes Toxins"}] },
      { name: "Spider Plant", scientific: "Chlorophytum comosum", icon: "🪴", freq: 7, health: [{icon:"🌬️", text:"Air Purifier"}, {icon:"🐾", text:"Pet Safe"}] },
      { name: "Peace Lily", scientific: "Spathiphyllum", icon: "🌸", freq: 5, health: [{icon:"🌬️", text:"Removes Mold Spores"}, {icon:"✨", text:"Purifies Air"}] },
      { name: "English Ivy", scientific: "Hedera helix", icon: "🌿", freq: 5, health: [{icon:"🫁", text:"Respiratory Support"}, {icon:"🌬️", text:"Air Purifier"}] },
      { name: "Boston Fern", scientific: "Nephrolepis exaltata", icon: "🌿", freq: 3, health: [{icon:"💧", text:"Natural Humidifier"}, {icon:"🌬️", text:"Air Purifier"}] },
      { name: "Golden Pothos", scientific: "Epipremnum aureum", icon: "🌿", freq: 7, health: [{icon:"🌬️", text:"Air Purifier"}, {icon:"😌", text:"Reduces Stress"}] },
      { name: "Rubber Plant", scientific: "Ficus elastica", icon: "🌳", freq: 7, health: [{icon:"🌬️", text:"Air Purifier"}, {icon:"🤧", text:"Hypoallergenic"}] },
      { name: "Areca Palm", scientific: "Dypsis lutescens", icon: "🌴", freq: 5, health: [{icon:"💧", text:"Natural Humidifier"}, {icon:"🌬️", text:"Air Purifier"}] },
      { name: "ZZ Plant", scientific: "Zamioculcas zamiifolia", icon: "🪴", freq: 21, health: [{icon:"🌬️", text:"Air Purifier"}, {icon:"✨", text:"Low Maintenance"}] },
      { name: "Monstera", scientific: "Monstera deliciosa", icon: "🪴", freq: 7, health: [{icon:"😌", text:"Mood Booster"}, {icon:"🌬️", text:"Air Purifier"}] },
      { name: "Philodendron", scientific: "Philodendron", icon: "🌿", freq: 7, health: [{icon:"🌬️", text:"Air Purifier"}, {icon:"😌", text:"Reduces Stress"}] },
      { name: "Aloe Arborescens", scientific: "Aloe arborescens", icon: "🪴", freq: 14, health: [{icon:"🧴", text:"Skin Healing"}, {icon:"🛡️", text:"Immunity"}] },
      { name: "Alocasia Polly", scientific: "Alocasia amazonica", icon: "🌿", freq: 5, health: [{icon:"✨", text:"Air Purifier"}] },
      { name: "Ficus Benjamina", scientific: "Ficus benjamina", icon: "🌳", freq: 7, health: [{icon:"🌬️", text:"Air Purifier"}] },
      { name: "Jade Plant", scientific: "Crassula ovata", icon: "🪴", freq: 14, health: [{icon:"🌬️", text:"Improves Air Quality"}] },
      
      // FLOWERS / ORNAMENTAL (WITH BENEFITS)
      { name: "Rose", scientific: "Rosa", icon: "🌹", freq: 3, health: [{icon:"😌", text:"Stress Relief"}, {icon:"🧴", text:"Skin Health"}] },
      { name: "Sunflower", scientific: "Helianthus annuus", icon: "🌻", freq: 3, health: [{icon:"😊", text:"Mood Enhancer"}, {icon:"🥜", text:"Nutritious Seeds"}] },
      { name: "Hibiscus", scientific: "Hibiscus rosa-sinensis", icon: "🌺", freq: 2, health: [{icon:"❤️", text:"Lowers Blood Pressure"}, {icon:"🛡️", text:"Antioxidants"}] },
      { name: "Jasmine", scientific: "Jasminum", icon: "🌼", freq: 3, health: [{icon:"😌", text:"Anxiety Relief"}, {icon:"💤", text:"Better Sleep"}] },
      { name: "Lotus", scientific: "Nelumbo nucifera", icon: "🪷", freq: 2, health: [{icon:"😌", text:"Calming"}, {icon:"🩸", text:"Stops Bleeding"}] },
      { name: "Marigold", scientific: "Tagetes", icon: "🏵️", freq: 3, health: [{icon:"🧴", text:"Skin Healing"}, {icon:"🦟", text:"Mosquito Repellent"}] },
      { name: "Orchid", scientific: "Orchidaceae", icon: "🌸", freq: 7, health: [{icon:"🌬️", text:"Night Air Purifier"}, {icon:"😌", text:"Reduces Stress"}] },
      { name: "Tulip", scientific: "Tulipa", icon: "🌷", freq: 4, health: [{icon:"😊", text:"Mood Booster"}] },
      { name: "Daisy", scientific: "Bellis perennis", icon: "🌼", freq: 3, health: [{icon:"🩹", text:"Wound Healing"}] },
      { name: "Chrysanthemum", scientific: "Chrysanthemum", icon: "🌼", freq: 3, health: [{icon:"🔥", text:"Anti-inflammatory"}, {icon:"🌬️", text:"Air Purifier"}] }
    ];`;

html = html.replace(/const plantDatabase = \[[\s\S]*?\];/, newDb);

fs.writeFileSync('index.html', html, 'utf8');
console.log('Successfully updated 100 plants DB');
